/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RectangleRouteImport } from './routes/rectangle'
import { Route as RhombusRouteImport } from './routes/rhombus'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RectangleRoute = RectangleRouteImport.update({
  id: '/rectangle',
  path: '/rectangle',
  getParentRoute: () => rootRouteImport,
} as any)
const RhombusRoute = RhombusRouteImport.update({
  id: '/rhombus',
  path: '/rhombus',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rectangle': typeof RectangleRoute
  '/rhombus': typeof RhombusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rectangle': typeof RectangleRoute
  '/rhombus': typeof RhombusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rectangle': typeof RectangleRoute
  '/rhombus': typeof RhombusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rectangle' | '/rhombus'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rectangle' | '/rhombus'
  id: '__root__' | '/' | '/rectangle' | '/rhombus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RectangleRoute: typeof RectangleRoute
  RhombusRoute: typeof RhombusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rectangle': {
      id: '/rectangle'
      path: '/rectangle'
      fullPath: '/rectangle'
      preLoaderRoute: typeof RectangleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rhombus': {
      id: '/rhombus'
      path: '/rhombus'
      fullPath: '/rhombus'
      preLoaderRoute: typeof RhombusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RectangleRoute: RectangleRoute,
  RhombusRoute: RhombusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
